simulation:
  name: "apartment"
  duration: 24h
  real_time_factor: 10.0  # 1 minute = 10 minutes
  max_devices: 30
  update_interval: 5s
  metrics_enabled: true
  metrics_port: 8080

mqtt:
  broker: "localhost"
  port: 1883
  username: ""
  password: ""
  client_prefix: "rtk_apt"
  keep_alive: 60s
  clean_session: true
  qos: 1
  retained: false
  tls_enabled: false

network:
  topology: "single_router"
  subnet: "192.168.1.0/24"
  internet_bandwidth: 50  # Typical apartment bandwidth
  dhcp_pool:
    start_ip: "192.168.1.100"
    end_ip: "192.168.1.150"
    lease_time: 12h
    gateway: "192.168.1.1"
    dns: ["8.8.8.8", "8.8.4.4"]
  interference:
    enabled: true
    environment_type: "apartment"
    wall_attenuation: 8.0  # Higher attenuation due to concrete walls
    sources:
      - type: "microwave"
        frequency: "2.4GHz"
        power: -10.0
        location: {x: 3.0, y: 2.0}
      - type: "neighbor_wifi"
        frequency: "2.4GHz"
        power: -30.0
        location: {x: -5.0, y: 0.0}
      - type: "neighbor_wifi"
        frequency: "5GHz"
        power: -35.0
        location: {x: 5.0, y: 0.0}
      - type: "neighbor_wifi"
        frequency: "2.4GHz"
        power: -32.0
        location: {x: 0.0, y: 5.0}

devices:
  network_devices:
    - id: "apartment_router"
      type: "router"
      tenant: "apartment"
      site: "living_room"
      ip_address: "192.168.1.1"
      connection_type: "ethernet"
      firmware: "1.5.0"
      protocols: ["wifi", "ethernet", "mqtt"]
      model: "Compact WiFi Router"
      wifi_bands: ["2.4GHz", "5GHz"]
      ethernet_ports: 4
      max_throughput: 50
      wifi_config:
        networks:
          - ssid: "ApartmentWiFi"
            band: "2.4GHz"
            hidden: false
            max_clients: 10
            tx_power: 18  # Lower power for apartment
          - ssid: "ApartmentWiFi_5G"
            band: "5GHz"
            hidden: false
            max_clients: 8
            tx_power: 20
        channels:
          channel_2g: 11  # Different channel to avoid interference
          channel_5g: 44
          auto_select: true
          width_2g: 20
          width_5g: 40  # Narrower channel width for apartments
        security:
          type: "WPA2"
          password: "apartment2024"
          encryption: "AES"

  iot_devices:
    - id: "living_room_light"
      type: "smart_bulb"
      tenant: "apartment"
      site: "living_room"
      connection_type: "wifi"
      firmware: "2.0.0"
      protocols: ["wifi", "mqtt"]
      category: "lighting"
      power_source: "ac"
      power_consumption: 9.0
      sensor_types: ["brightness"]
      control_types: ["power", "brightness", "color"]
      extra:
        max_brightness: 800
        color_temperature_range: [2700, 5000]
        rgb_support: true

    - id: "bedroom_light"
      type: "smart_bulb"
      tenant: "apartment"
      site: "bedroom"
      connection_type: "wifi"
      firmware: "2.0.0"
      protocols: ["wifi", "mqtt"]
      category: "lighting"
      power_source: "ac"
      power_consumption: 9.0
      sensor_types: ["brightness"]
      control_types: ["power", "brightness"]

    - id: "kitchen_light"
      type: "smart_bulb"
      tenant: "apartment"
      site: "kitchen"
      connection_type: "wifi"
      firmware: "2.0.0"
      protocols: ["wifi", "mqtt"]
      category: "lighting"
      power_source: "ac"
      power_consumption: 12.0
      sensor_types: ["brightness"]
      control_types: ["power", "brightness"]

    - id: "portable_ac"
      type: "air_conditioner"
      tenant: "apartment"
      site: "living_room"
      connection_type: "wifi"
      firmware: "2.5.0"
      protocols: ["wifi", "mqtt"]
      category: "climate"
      power_source: "ac"
      power_consumption: 900.0  # Portable AC unit
      sensor_types: ["temperature", "humidity"]
      control_types: ["power", "temperature", "fan_speed", "mode"]
      extra:
        cooling_capacity: 8000
        portable: true
        energy_rating: "A"

    - id: "smart_thermostat"
      type: "smart_thermostat"
      tenant: "apartment"
      site: "hallway"
      connection_type: "wifi"
      firmware: "3.0.0"
      protocols: ["wifi", "mqtt"]
      category: "climate"
      power_source: "battery"
      power_consumption: 2.0
      sensor_types: ["temperature", "humidity"]
      control_types: ["temperature_setpoint", "mode"]
      extra:
        battery_level: 95
        learning_mode: false  # Disabled for rental

    - id: "living_room_sensor"
      type: "environmental_sensor"
      tenant: "apartment"
      site: "living_room"
      connection_type: "wifi"
      firmware: "1.3.0"
      protocols: ["wifi", "mqtt"]
      category: "sensor"
      power_source: "battery"
      power_consumption: 0.5
      sensor_types: ["temperature", "humidity", "co2"]
      extra:
        battery_level: 80
        compact_design: true

    - id: "door_camera"
      type: "security_camera"
      tenant: "apartment"
      site: "entrance"
      connection_type: "wifi"
      firmware: "4.0.0"
      protocols: ["wifi", "mqtt"]
      category: "security"
      power_source: "usb"
      power_consumption: 5.0
      sensor_types: ["motion", "sound"]
      control_types: ["recording"]
      extra:
        resolution: "1080p"
        fps: 24
        storage_type: "local"
        indoor_use: true

    - id: "smart_plug_desk"
      type: "smart_plug"
      tenant: "apartment"
      site: "bedroom"
      connection_type: "wifi"
      firmware: "1.1.0"
      protocols: ["wifi", "mqtt"]
      category: "power"
      power_source: "ac"
      power_consumption: 1.0
      sensor_types: ["power_usage"]
      control_types: ["power", "schedule"]
      extra:
        max_load: 2400
        compact_size: true

    - id: "smart_plug_fan"
      type: "smart_plug"
      tenant: "apartment"
      site: "living_room"
      connection_type: "wifi"
      firmware: "1.1.0"
      protocols: ["wifi", "mqtt"]
      category: "power"
      power_source: "ac"
      power_consumption: 1.0
      sensor_types: ["power_usage"]
      control_types: ["power", "timer"]

  client_devices:
    - id: "smartphone_resident"
      type: "smartphone"
      tenant: "apartment"
      site: "mobile"
      connection_type: "wifi"
      firmware: "Android 14"
      protocols: ["wifi", "bluetooth", "cellular"]
      device_class: "smartphone"
      operating_system: "Android"
      usage_profile:
        profile: "moderate"
        daily_hours: 6.0
        peak_hours:
          - start_time: "07:00"
            end_time: "08:30"
            days: ["monday", "tuesday", "wednesday", "thursday", "friday"]
          - start_time: "18:00"
            end_time: "22:00"
            days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
      network_behavior:
        preferred_band: "5GHz"
        roaming_enabled: false  # Single AP
        power_save_mode: true

    - id: "laptop_work"
      type: "laptop"
      tenant: "apartment"
      site: "bedroom"
      connection_type: "wifi"
      firmware: "Ubuntu 22.04"
      protocols: ["wifi", "bluetooth"]
      device_class: "laptop"
      operating_system: "Linux"
      usage_profile:
        profile: "work"
        daily_hours: 8.0
        peak_hours:
          - start_time: "09:00"
            end_time: "17:00"
            days: ["monday", "tuesday", "wednesday", "thursday", "friday"]
      network_behavior:
        preferred_band: "5GHz"
        bandwidth_usage:
          typical_upload: 200
          typical_download: 1500
          peak_upload: 1000
          peak_download: 5000

    - id: "tablet_personal"
      type: "tablet"
      tenant: "apartment"
      site: "living_room"
      connection_type: "wifi"
      firmware: "Android 13"
      protocols: ["wifi", "bluetooth"]
      device_class: "tablet"
      operating_system: "Android"
      usage_profile:
        profile: "entertainment"
        daily_hours: 3.0
        peak_hours:
          - start_time: "19:00"
            end_time: "22:00"
            days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]

    - id: "smart_tv"
      type: "smart_tv"
      tenant: "apartment"
      site: "living_room"
      connection_type: "wifi"
      firmware: "Roku OS 12"
      protocols: ["wifi"]
      device_class: "smart_tv"
      operating_system: "Roku"
      usage_profile:
        profile: "entertainment"
        daily_hours: 4.0
        peak_hours:
          - start_time: "18:00"
            end_time: "23:00"
            days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
      network_behavior:
        preferred_band: "5GHz"
        bandwidth_usage:
          typical_download: 5000  # Streaming
          peak_download: 15000    # 4K streaming

scenarios:
  - name: "apartment_daily"
    description: "Typical apartment daily routine"
    duration: 24h
    events:
      - time: 7h
        type: "wake_up"
        target: "all_devices"
        parameters:
          bedroom_light_on: true
          bathroom_light_on: true
          morning_temperature: 21.0
        probability: 0.9
      
      - time: 8h30m
        type: "leave_for_work"
        target: "all_devices"
        parameters:
          all_lights_off: true
          ac_eco_mode: true
          security_armed: true
        probability: 0.85
      
      - time: 12h30m
        type: "lunch_wfh"
        target: "kitchen_devices"
        parameters:
          kitchen_active: true
        probability: 0.3  # Some days WFH
      
      - time: 18h
        type: "return_home"
        target: "all_devices"
        parameters:
          entrance_light_on: true
          ac_comfort_mode: true
          security_disarmed: true
        probability: 0.85
      
      - time: 19h
        type: "dinner_prep"
        target: "kitchen_devices"
        parameters:
          kitchen_lights_bright: true
          exhaust_fan: true
        probability: 0.8
      
      - time: 20h
        type: "relax_time"
        target: "living_room_devices"
        parameters:
          tv_on: true
          lights_dimmed: true
        probability: 0.7
      
      - time: 23h
        type: "bedtime"
        target: "all_devices"
        parameters:
          all_lights_off: true
          ac_night_mode: true
          tv_off: true
        probability: 0.9

  - name: "weekend_apartment"
    description: "Weekend routine in apartment"
    duration: 48h
    conditions:
      - type: "day_of_week"
        parameters:
          days: ["saturday", "sunday"]
    events:
      - time: 9h
        type: "weekend_morning"
        target: "all_devices"
        parameters:
          gradual_wake: true
          coffee_ready: true
        probability: 0.7
      
      - time: 14h
        type: "weekend_activity"
        target: "all_devices"
        parameters:
          music_streaming: true
          cleaning_mode: true
        probability: 0.5
      
      - time: 20h
        type: "weekend_entertainment"
        target: "entertainment_devices"
        parameters:
          movie_night: true
          surround_mode: true
        probability: 0.6

  - name: "quiet_hours"
    description: "Apartment building quiet hours"
    duration: 24h
    events:
      - time: 22h
        type: "quiet_mode_start"
        target: "all_devices"
        parameters:
          reduce_volume: true
          dim_lights: true
          reduce_activity: true
        probability: 1.0
      
      - time: 7h
        type: "quiet_mode_end"
        target: "all_devices"
        parameters:
          normal_operation: true
        probability: 1.0

logging:
  level: "info"
  format: "text"
  output: "stdout"
  device_specific: false
  max_size: 100
  max_age: 7
  max_backups: 3
  compress: false