simulation:
  name: "home_advanced"
  duration: 24h
  real_time_factor: 60.0  # 1 minute = 1 hour
  max_devices: 50
  update_interval: 5s
  metrics_enabled: true
  metrics_port: 8080

mqtt:
  broker: "localhost"
  port: 1883
  username: ""
  password: ""
  client_prefix: "rtk_advanced"
  keep_alive: 60s
  clean_session: true
  qos: 1
  retained: true
  tls_enabled: false

network:
  topology: "mesh_network"
  subnet: "192.168.1.0/24"
  internet_bandwidth: 300
  vlans:
    - id: 10
      name: "main"
      subnet: "192.168.10.0/24"
    - id: 20
      name: "iot"
      subnet: "192.168.20.0/24"
    - id: 30
      name: "guest"
      subnet: "192.168.30.0/24"
  dhcp_pool:
    start_ip: "192.168.1.100"
    end_ip: "192.168.1.250"
    lease_time: 24h
    gateway: "192.168.1.1"
    dns: ["8.8.8.8", "8.8.4.4", "1.1.1.1"]
  interference:
    enabled: true
    environment_type: "suburban_home"
    wall_attenuation: 6.0
    sources:
      - type: "microwave"
        frequency: "2.4GHz"
        power: -10.0
        location: {x: 5.0, y: 3.0}
      - type: "bluetooth"
        frequency: "2.4GHz"
        power: -20.0
        location: {x: 10.0, y: 8.0}
      - type: "neighbor_wifi"
        frequency: "2.4GHz"
        power: -40.0
        location: {x: -5.0, y: 0.0}

devices:
  network_devices:
    - id: "main_router"
      type: "router"
      tenant: "home"
      site: "living_room"
      ip_address: "192.168.1.1"
      connection_type: "ethernet"
      firmware: "2.0.0"
      protocols: ["wifi", "ethernet", "mqtt"]
      model: "Advanced WiFi 6 Router"
      wifi_bands: ["2.4GHz", "5GHz", "6GHz"]
      ethernet_ports: 8
      max_throughput: 1000
      wifi_config:
        networks:
          - ssid: "HomeNetwork"
            band: "2.4GHz"
            hidden: false
            max_clients: 30
            tx_power: 20
          - ssid: "HomeNetwork_5G"
            band: "5GHz"
            hidden: false
            max_clients: 25
            tx_power: 23
          - ssid: "HomeNetwork_6G"
            band: "6GHz"
            hidden: false
            max_clients: 20
            tx_power: 23
        channels:
          channel_2g: 6
          channel_5g: 36
          channel_6g: 1
          auto_select: true
          width_2g: 20
          width_5g: 80
          width_6g: 160
        security:
          type: "WPA3"
          password: "advancedhome123!@#"
          encryption: "AES"

    - id: "mesh_node_upstairs"
      type: "mesh_node"
      tenant: "home"
      site: "upstairs_hallway"
      ip_address: "192.168.1.2"
      connection_type: "wireless"
      firmware: "2.0.0"
      protocols: ["wifi", "mqtt"]
      model: "Mesh Node Pro"
      wifi_bands: ["2.4GHz", "5GHz"]
      mesh_role: "satellite"
      backhaul_type: "wireless"
      parent_node: "main_router"

    - id: "mesh_node_basement"
      type: "mesh_node"
      tenant: "home"
      site: "basement"
      ip_address: "192.168.1.3"
      connection_type: "ethernet"
      firmware: "2.0.0"
      protocols: ["wifi", "ethernet", "mqtt"]
      model: "Mesh Node Pro"
      wifi_bands: ["2.4GHz", "5GHz"]
      mesh_role: "satellite"
      backhaul_type: "ethernet"
      parent_node: "main_router"

    - id: "managed_switch"
      type: "switch"
      tenant: "home"
      site: "network_closet"
      ip_address: "192.168.1.4"
      connection_type: "ethernet"
      firmware: "1.5.0"
      protocols: ["ethernet", "mqtt"]
      model: "24-Port Managed Switch"
      port_count: 24
      poe_ports: 8
      vlan_support: true

  iot_devices:
    - id: "living_room_light_1"
      type: "smart_bulb"
      tenant: "home"
      site: "living_room"
      connection_type: "wifi"
      firmware: "2.1.0"
      protocols: ["wifi", "mqtt"]
      category: "lighting"
      power_source: "ac"
      power_consumption: 9.0
      sensor_types: ["brightness", "color_temperature"]
      control_types: ["power", "brightness", "color", "scene"]
      extra:
        max_brightness: 1000
        color_temperature_range: [2700, 6500]
        rgb_support: true

    - id: "living_room_light_2"
      type: "smart_bulb"
      tenant: "home"
      site: "living_room"
      connection_type: "wifi"
      firmware: "2.1.0"
      protocols: ["wifi", "mqtt"]
      category: "lighting"
      power_source: "ac"
      power_consumption: 9.0
      sensor_types: ["brightness", "color_temperature"]
      control_types: ["power", "brightness", "color", "scene"]

    - id: "kitchen_light"
      type: "smart_bulb"
      tenant: "home"
      site: "kitchen"
      connection_type: "wifi"
      firmware: "2.1.0"
      protocols: ["wifi", "mqtt"]
      category: "lighting"
      power_source: "ac"
      power_consumption: 12.0
      sensor_types: ["brightness"]
      control_types: ["power", "brightness"]

    - id: "bedroom_light"
      type: "smart_bulb"
      tenant: "home"
      site: "master_bedroom"
      connection_type: "wifi"
      firmware: "2.1.0"
      protocols: ["wifi", "mqtt"]
      category: "lighting"
      power_source: "ac"
      power_consumption: 9.0
      sensor_types: ["brightness", "color_temperature"]
      control_types: ["power", "brightness", "color", "scene"]

    - id: "living_room_ac"
      type: "air_conditioner"
      tenant: "home"
      site: "living_room"
      connection_type: "wifi"
      firmware: "3.0.1"
      protocols: ["wifi", "mqtt"]
      category: "climate"
      power_source: "ac"
      power_consumption: 1800.0
      sensor_types: ["temperature", "humidity", "air_quality"]
      control_types: ["power", "temperature", "fan_speed", "mode", "swing"]
      extra:
        cooling_capacity: 18000
        heating_capacity: 16000
        energy_rating: "A++"

    - id: "bedroom_ac"
      type: "air_conditioner"
      tenant: "home"
      site: "master_bedroom"
      connection_type: "wifi"
      firmware: "3.0.1"
      protocols: ["wifi", "mqtt"]
      category: "climate"
      power_source: "ac"
      power_consumption: 1200.0
      sensor_types: ["temperature", "humidity"]
      control_types: ["power", "temperature", "fan_speed", "mode"]

    - id: "smart_thermostat"
      type: "smart_thermostat"
      tenant: "home"
      site: "hallway"
      connection_type: "wifi"
      firmware: "4.2.0"
      protocols: ["wifi", "mqtt"]
      category: "climate"
      power_source: "battery"
      power_consumption: 2.0
      sensor_types: ["temperature", "humidity", "occupancy"]
      control_types: ["temperature_setpoint", "mode", "schedule"]
      extra:
        battery_level: 85
        learning_mode: true

    - id: "kitchen_sensor"
      type: "environmental_sensor"
      tenant: "home"
      site: "kitchen"
      connection_type: "wifi"
      firmware: "1.5.0"
      protocols: ["wifi", "mqtt"]
      category: "sensor"
      power_source: "battery"
      power_consumption: 0.5
      sensor_types: ["temperature", "humidity", "gas", "smoke"]
      extra:
        battery_level: 90
        alarm_enabled: true

    - id: "bathroom_sensor"
      type: "environmental_sensor"
      tenant: "home"
      site: "bathroom"
      connection_type: "wifi"
      firmware: "1.5.0"
      protocols: ["wifi", "mqtt"]
      category: "sensor"
      power_source: "battery"
      power_consumption: 0.5
      sensor_types: ["temperature", "humidity", "motion"]
      extra:
        battery_level: 75

    - id: "front_door_camera"
      type: "security_camera"
      tenant: "home"
      site: "front_entrance"
      connection_type: "wifi"
      firmware: "5.0.2"
      protocols: ["wifi", "mqtt", "rtsp"]
      category: "security"
      power_source: "poe"
      power_consumption: 15.0
      sensor_types: ["motion", "sound", "light"]
      control_types: ["recording", "night_vision", "ptz"]
      extra:
        resolution: "4K"
        fps: 30
        storage_type: "cloud"
        night_vision: true

    - id: "backyard_camera"
      type: "security_camera"
      tenant: "home"
      site: "backyard"
      connection_type: "wifi"
      firmware: "5.0.2"
      protocols: ["wifi", "mqtt", "rtsp"]
      category: "security"
      power_source: "ac"
      power_consumption: 12.0
      sensor_types: ["motion", "sound"]
      control_types: ["recording", "night_vision"]

    - id: "smart_plug_tv"
      type: "smart_plug"
      tenant: "home"
      site: "living_room"
      connection_type: "wifi"
      firmware: "1.2.0"
      protocols: ["wifi", "mqtt"]
      category: "power"
      power_source: "ac"
      power_consumption: 1.0
      sensor_types: ["power_usage", "voltage"]
      control_types: ["power", "schedule", "timer"]
      extra:
        max_load: 3600
        current_load: 250

    - id: "smart_plug_lamp"
      type: "smart_plug"
      tenant: "home"
      site: "bedroom"
      connection_type: "wifi"
      firmware: "1.2.0"
      protocols: ["wifi", "mqtt"]
      category: "power"
      power_source: "ac"
      power_consumption: 1.0
      sensor_types: ["power_usage"]
      control_types: ["power", "schedule"]

  client_devices:
    - id: "smartphone_john"
      type: "smartphone"
      tenant: "home"
      site: "mobile"
      connection_type: "wifi"
      firmware: "iOS 17"
      protocols: ["wifi", "bluetooth", "cellular"]
      device_class: "smartphone"
      operating_system: "iOS"
      usage_profile:
        profile: "heavy"
        daily_hours: 8.0
        peak_hours:
          - start_time: "07:00"
            end_time: "09:00"
            days: ["monday", "tuesday", "wednesday", "thursday", "friday"]
          - start_time: "12:00"
            end_time: "13:00"
            days: ["monday", "tuesday", "wednesday", "thursday", "friday"]
          - start_time: "18:00"
            end_time: "23:00"
            days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
      network_behavior:
        preferred_band: "5GHz"
        roaming_enabled: true
        power_save_mode: false

    - id: "smartphone_mary"
      type: "smartphone"
      tenant: "home"
      site: "mobile"
      connection_type: "wifi"
      firmware: "Android 14"
      protocols: ["wifi", "bluetooth"]
      device_class: "smartphone"
      operating_system: "Android"
      usage_profile:
        profile: "moderate"
        daily_hours: 5.0

    - id: "laptop_john"
      type: "laptop"
      tenant: "home"
      site: "office"
      connection_type: "wifi"
      firmware: "Windows 11"
      protocols: ["wifi", "ethernet", "bluetooth"]
      device_class: "laptop"
      operating_system: "Windows"
      usage_profile:
        profile: "work"
        daily_hours: 10.0
        peak_hours:
          - start_time: "09:00"
            end_time: "17:00"
            days: ["monday", "tuesday", "wednesday", "thursday", "friday"]

    - id: "laptop_mary"
      type: "laptop"
      tenant: "home"
      site: "living_room"
      connection_type: "wifi"
      firmware: "macOS 14"
      protocols: ["wifi", "bluetooth"]
      device_class: "laptop"
      operating_system: "macOS"
      usage_profile:
        profile: "work"
        daily_hours: 8.0

    - id: "tablet_kids"
      type: "tablet"
      tenant: "home"
      site: "kids_room"
      connection_type: "wifi"
      firmware: "iPadOS 17"
      protocols: ["wifi", "bluetooth"]
      device_class: "tablet"
      operating_system: "iPadOS"
      usage_profile:
        profile: "entertainment"
        daily_hours: 3.0
        peak_hours:
          - start_time: "15:00"
            end_time: "18:00"
            days: ["monday", "tuesday", "wednesday", "thursday", "friday"]
          - start_time: "10:00"
            end_time: "12:00"
            days: ["saturday", "sunday"]

    - id: "smart_tv_living"
      type: "smart_tv"
      tenant: "home"
      site: "living_room"
      connection_type: "wifi"
      firmware: "webOS 6.0"
      protocols: ["wifi", "ethernet"]
      device_class: "smart_tv"
      operating_system: "webOS"
      usage_profile:
        profile: "entertainment"
        daily_hours: 4.0
        peak_hours:
          - start_time: "19:00"
            end_time: "23:00"
            days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]

    - id: "smart_tv_bedroom"
      type: "smart_tv"
      tenant: "home"
      site: "master_bedroom"
      connection_type: "wifi"
      firmware: "Android TV 12"
      protocols: ["wifi"]
      device_class: "smart_tv"
      operating_system: "Android TV"
      usage_profile:
        profile: "entertainment"
        daily_hours: 2.0

scenarios:
  - name: "advanced_daily_routine"
    description: "Advanced home with automated routines"
    duration: 24h
    events:
      - time: 6h30m
        type: "morning_wakeup"
        target: "all_devices"
        parameters:
          lights_on: ["bedroom_light", "bathroom_sensor"]
          ac_adjust: true
          target_temperature: 22.0
        probability: 0.9
      
      - time: 7h
        type: "morning_routine"
        target: "all_devices"
        parameters:
          kitchen_active: true
          news_on_tv: true
          coffee_maker: true
        probability: 0.85
      
      - time: 8h30m
        type: "leave_home"
        target: "all_devices"
        parameters:
          security_arm: true
          lights_off: true
          ac_eco_mode: true
        probability: 0.8
      
      - time: 17h30m
        type: "arrive_home"
        target: "all_devices"
        parameters:
          security_disarm: true
          welcome_lights: true
          ac_comfort_mode: true
        probability: 0.85
      
      - time: 19h
        type: "dinner_time"
        target: "kitchen_devices"
        parameters:
          kitchen_lights_bright: true
          dining_scene: true
        probability: 0.9
      
      - time: 20h30m
        type: "entertainment_time"
        target: "living_room_devices"
        parameters:
          tv_on: true
          lights_dim: true
          surround_sound: true
        probability: 0.7
      
      - time: 22h30m
        type: "bedtime_routine"
        target: "all_devices"
        parameters:
          gradual_lights_off: true
          ac_sleep_mode: true
          security_night_mode: true
        probability: 0.9

  - name: "smart_automation"
    description: "Smart home automation based on occupancy"
    duration: 24h
    events:
      - time: 0h
        type: "occupancy_based_control"
        target: "all_sensors"
        parameters:
          motion_triggered_lights: true
          presence_based_ac: true
          auto_security: true
        probability: 1.0

  - name: "energy_optimization"
    description: "Energy saving patterns"
    duration: 24h
    events:
      - time: 9h
        type: "peak_avoidance"
        target: "high_power_devices"
        parameters:
          shift_load: true
          optimize_ac: true
          dim_lights: 20
        probability: 0.7
      
      - time: 14h
        type: "solar_peak"
        target: "all_devices"
        parameters:
          maximize_usage: true
          charge_batteries: true
        probability: 0.6

logging:
  level: "info"
  format: "json"
  output: "file"
  file_path: "logs/home_advanced.log"
  device_specific: true
  max_size: 500
  max_age: 30
  max_backups: 10
  compress: true