mqtt:
  broker_host: "localhost"
  broker_port: 1883
  client_id: "ff:ee:dd:cc:bb:aa"
  username: ""
  password: ""
  keep_alive: "60s"
  clean_session: true
  connect_timeout: "30s"
  retry_interval: "5s"
  max_retry_count: 3
  tls: false
  lwt:
    topic: "rtk/v1/demo/office/ff:ee:dd:cc:bb:aa/lwt"
    message: '{"status": "offline", "timestamp": "2024-01-01T00:00:00Z"}'
    qos: 1
    retained: true

device:
  type: "framework_demo"
  tenant: "demo"
  site: "office"
  device_id: "ff:ee:dd:cc:bb:aa"
  name: "RTK Framework Demo"
  description: "Demonstration of the complete RTK MQTT framework capabilities"
  version: "1.0.0"
  metadata:
    purpose: "demonstration"
    environment: "development"
  state_interval: "30s"
  telemetry_interval: "60s"
  heartbeat_interval: "300s"

logging:
  level: "info"
  format: "text"
  output: "stdout"

plugins:
  directory: "./plugins"
  enabled: ["demo"]
  config:
    demo:
      update_interval: "10s"
      demo_mode: true