mqtt:
  broker_host: "localhost"
  broker_port: 1883
  client_id: "aa:bb:cc:dd:ee:ff"
  username: ""
  password: ""
  keep_alive: "60s"
  clean_session: true
  connect_timeout: "30s"
  retry_interval: "5s"
  max_retry_count: 3
  tls: false
  lwt:
    topic: "rtk/v1/demo/office/aa:bb:cc:dd:ee:ff/lwt"
    message: '{"status": "offline", "timestamp": "2024-01-01T00:00:00Z"}'
    qos: 1
    retained: true

device:
  type: "wifi_router"
  tenant: "demo"
  site: "office"
  device_id: "aa:bb:cc:dd:ee:ff"
  name: "Office WiFi Router"
  description: "Main WiFi router for office network with diagnostic capabilities"
  version: "1.0.0"
  metadata:
    location: "Office Network Closet"
    model: "RTK-WR-1000"
    firmware: "1.2.3"
  state_interval: "30s"
  telemetry_interval: "60s"
  heartbeat_interval: "300s"

logging:
  level: "info"
  format: "text"
  output: "stdout"

plugins:
  directory: "./plugins"
  enabled: ["wifi_router"]
  config:
    wifi_router:
      ssid: "RTK_Demo_Network"
      channel: 6
      max_clients: 50
      diagnostic_interval: "60s"
      event_reporting: true