mqtt:
  broker_host: "localhost"
  broker_port: 1883
  client_id: "00:11:22:33:44:55"
  username: ""
  password: ""
  keep_alive: "60s"
  clean_session: true
  connect_timeout: "30s"
  retry_interval: "5s"
  max_retry_count: 3
  tls: false
  lwt:
    topic: "rtk/v1/demo/office/00:11:22:33:44:55/lwt"
    message: '{"status": "offline", "timestamp": "2024-01-01T00:00:00Z"}'
    qos: 1
    retained: true

device:
  type: "iot_sensor"
  tenant: "demo"
  site: "office"
  device_id: "00:11:22:33:44:55"
  name: "Office Environmental Sensor"
  description: "Temperature, humidity, and pressure sensor for office monitoring"
  version: "1.0.0"
  metadata:
    location: "Office Room 101"
    zone: "Building A"
  state_interval: "30s"
  telemetry_interval: "60s"
  heartbeat_interval: "300s"

logging:
  level: "info"
  format: "text"
  output: "stdout"

plugins:
  directory: "./plugins"
  enabled: ["iot_sensor"]
  config:
    iot_sensor:
      sensor_type: "environmental"
      reading_interval: "5s"
      telemetry_interval: "30s"